/* Crear 7 sinonimos (Uno para cada tabla) */

CREATE SYNONYM E FOR EMPLEADOS_LEOR;
SELECT * FROM E;
CREATE SYNONYM R FOR REGIONES_LEOR;
SELECT * FROM R;
CREATE SYNONYM JH_D FOR HISTORIAL_PUESTOS_LEOR;
SELECT * FROM JH_D;
CREATE SYNONYM D FOR DEPARTAMENTOS_LEOR;
SELECT * FROM D;
CREATE SYNONYM UP FOR UBICACIONES_LEOR;
SELECT * FROM UP;
CREATE SYNONYM PR FOR PAISES_LEOR;
SELECT * FROM PR;
CREATE SYNONYM P FOR PUESTOS_LEOR;
SELECT * FROM P;

/* Crear las secuencias necesarias para los IDs de las tablas en RH para las llaves primarias
   Consideraciones: 
*/
CREATE SEQUENCE SEQ_REG_PK START WITH 5 INCREMENT BY 1 MAXVALUE 100 NOCYCLE;
SELECT SEQ_REG_PK.NEXTVAL FROM DUAL;
DROP SEQUENCE SEQ_REG_PK;
CREATE SEQUENCE SEQ_UBIC_PK START WITH 3300 INCREMENT BY 100 MAXVALUE 10000 NOCYCLE;
SELECT SEQ_UBIC_PK.NEXTVAL FROM DUAL;
DROP SEQUENCE SEQ_UBIC_PK;
CREATE SEQUENCE SEQ_EMP_PK START WITH 207 INCREMENT BY 1 MAXVALUE 500 NOCYCLE;
SELECT SEQ_EMP_PK.NEXTVAL FROM DUAL;
DROP SEQUENCE SEQ_EMP_PK;
CREATE SEQUENCE SEQ_DEP_PK START WITH 280 INCREMENT BY 10 MAXVALUE 1000 NOCYCLE;
SELECT SEQ_DEP_PK.NEXTVAL FROM DUAL;
DROP SEQUENCE SEQ_DEP_PK;


/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 01.     ID_REGION                     NO         ES PK EN SU TABLA
 02.     NOMBRE_REGION                 NO         CONTIENE POCOS REGISTROS
*/
/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 03.     ID_PAIS                       NO         ES PK EN SU TABLA
 04.     NOMBRE_PAIS                   SI         TIENE MUCHOS REGISTROS DIFERENTES
 05.     PAISES.ID_REGION              SI         PORQUE SE UTILIZA MUCHO EN JOINS
*/
CREATE UNIQUE INDEX NOM_PAIS_UK ON PAISES_LEOR(NOMBRE_PAIS);
CREATE INDEX ID_REGION_PAIS ON PAISES_LEOR(ID_REGION);
/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 06.     UBICACIONES.ID_UBICACION      NO         ES PK EN SU TABLA
 07.     UBICACIONES.DIRECCION         NO         TIENE MUCHOS REGISTROS DIFERENTES
 08.     UBICACIONES.CODIGO_POSTAL     NO         NO ES MUY USADA EN UNIONES
 09.     UBICACIONES.COUDAD            NO         NO ES MUY USADA EN UNIONES
 10.     UBICACIONES.ESTADO            SI         CONTIENE VALORES NULOS
 11.     UBICACIONES.ID_PAIS           SI         ES MUY USADO EN JOINS
*/
CREATE UNIQUE INDEX DIR_UBIC ON UBICACIONES_LEOR(DIRECCION);
CREATE INDEX ESTADO_UBIC ON UBICACIONES_LEOR(ID_APIS);
CREATE INDEX ID_PAIS_UBIC ON UBICACIONES_LEOR(ID_PAIS);
/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 12.     PUESTO.ID_PUESTO             NO         ES PK EN SU TABLA
 13.     PUESTO.TITULO_PUESTO         NO         SON DATOS VARIADOS PERO NO USADOS FRECUENTEMENTE EN CONSULTAS O JOINS
 13.     PUESTO.SALARIO_MIN           SI         MUCHOS VALORES Y USADOS EN WHERE O JOINS
 13.     PUESTO.SALARIO_MAX           SI         MUCHOS VALORES Y USADOS EN WHERE O JOINS
*/
CREATE INDEX SALARIO_MIN_PUESTO ON PUESTOS_LEOR(SALARIO_MAX);
CREATE INDEX SALARIO_MAX_PUESTO ON PUESTOS_LEOR(SALARIO_MIN);
/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 14.     HISTORIAL.ID_EMPLEADO         NO         ES PARTE DE LA PK EN SU TABLA
 15.     HISTORIAL.FECHA_INICIO        NO         ES PARTE DE LA PK EN SU TABLA
 16.     HISTORIAL.FECHA_FIN           NO         SON DATOS VARIADOS PERO NO USADOS FRECUENTEMENTE EN CONSULTAS O JOINS
 17.     HISTORIAL.ID_PUESTO           SI         USADOS FRECUENTEMENTE EN WHERE O JOINS
 18.     HISTORIAL.ID_DEPARTAMENTO     SI         USADOS FRECUENTEMENTE EN WHERE O JOINS
*/
CREATE INDEX PUESTO_HISTORIAL ON HISTORIAL_PUESTOS_LEOR(ID_PUESTO);
CREATE INDEX DEPARTAMENTO_HISTORIAL ON HISTORIAL_PUESTOS_LEOR(ID_DEPARTAMENTO);
/* Crear indices
 N       COLUMNA                       REQUIERE   INDICE JUSTIFICACION
 19.     EMPLEADOS.ID_EMPLEADO         NO         ES PARTE DE LA PK EN SU TABLA
 20.     EMPLEADOS.NOMBRE              NO         NO ES USADO PARA WHERE O JOINS
 21.     EMPLEADOS.APELLIDO            SI         NO ES FRECUENTEMENTE PARA WHERE O JOINS
 22.     EMPLEADOS.CORREO              NO         SON UNICOS Y USADOS EN CONSULTAS
 23.     EMPLEADOS.TELEFONO            NO         NO ES USADO PARA WHERE O JOINS
 24.     EMPLEADOS.FECHA_CONTRATACION  NO         NO ES FRECUENTEMENTE PARA WHERE O JOINS
 25.     EMPLEADOS.ID_PUESTO           SI         USADO FRECUENTEMENTE PARA WHERE O JOINS
 26.     EMPLEADOS.ID_GERENTE          SI         USADO FRECUENTEMENTE PARA WHERE O JOINS
 27.     EMPLEADOS.ID_DEPARTAMENTO     SI         USADO FRECUENTEMENTE PARA WHERE O JOINS
 28.     EMPLEADOS.SALARION            SI         NO ES USADO PARA WHERE O JOINS
 29.     EMPLEADOS.COMISION            SI         ENO ES USADO PARA WHERE O JOINS
 30.     DEPARTAMENTOS.ID_DEPARTAMENTO NO         ES PARTE DE LA PK EN SU TABLA
*/
CREATE INDEX APELLIDO_EMP ON EMPLEADOS_LEOR(APELLIDO);
CREATE INDEX PUESTO_EMP ON EMPLEADOS_LEOR(ID_PUESTO);
CREATE INDEX GERENTE_EMP ON EMPLEADOS_LEOR(ID_GERENTE);
CREATE INDEX DEPARTAMENTO_EMP ON EMPLEADOS_LEOR(ID_DEPARTAMENTO);
CREATE INDEX SALARIO_EMP ON EMPLEADOS_LEOR(SALARIO);
CREATE INDEX COMISION_EMP ON EMPLEADOS_LEOR(COMISION);


