CREATE TABLE TIPO_HABITACION (
ID_TIPO NUMBER(3) CONSTRAINT TIPO_HABITACION_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100) CONSTRAINT TIPO_HABITACION_DESC_NN NOT NULL
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA NUMBER(3) CONSTRAINT CATEGORIA_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(100) CONSTRAINT CATEGORIA_DESC_NN NOT NULL,
IVA NUMBER(4, 2)
);

CREATE TABLE AGENCIA (
ID_AGENCIA NUMBER(5) CONSTRAINT AGENCIA_PK PRIMARY KEY,
TELEFONO VARCHAR2(20) CONSTRAINT AGENCIA_TEL_NN NOT NULL,
NOMBRE VARCHAR2(30) CONSTRAINT AGENCIA_NOM_NN NOT NULL,
COLONIA VARCHAR2(30) CONSTRAINT AGENCIA_COL_NN NOT NULL,
CALLE VARCHAR2(30),
CONSTRAINT AGENCIA_TEL_UK UNIQUE(TELEFONO)
);

CREATE TABLE EMPLEADO (
ID_EMPLEADO NUMBER(10) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
TELEFONO VARCHAR2(20) CONSTRAINT EMPLEADO_TEL_NN NOT NULL,
NOMBRE VARCHAR2(30) CONSTRAINT EMPLEADO_NOM_NN NOT NULL,
APELLIDO_PATERNO VARCHAR2(30) CONSTRAINT EMPLEADO_APPATERNO_NN NOT NULL,
APELLIDO_MATERNO VARCHAR2(30) CONSTRAINT EMPLEADO_APMATERNO_NN NOT NULL,
CONSTRAINT EMPLEADO_TEL_UK UNIQUE(TELEFONO)
);


CREATE TABLE EMPLEADO_AGENCIA(
ID_EMPLEADO_AGENCIA NUMBER(10) CONSTRAINT EMPLEADO_AGENCIA_PK PRIMARY KEY,
ID_EMPLEADO NUMBER(10),
ID_AGENCIA NUMBER(5),
CONSTRAINT EMP_AG_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
CONSTRAINT EMP_AG_AGENCIA_FK FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA(ID_AGENCIA)
);

CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(10) CONSTRAINT CLIENTE_PK PRIMARY KEY,
TELEFONO VARCHAR2(20) CONSTRAINT CLIENTE_TEL_NN NOT NULL,
NOMBRE VARCHAR2(30) CONSTRAINT CLIENTE_NOM_NN NOT NULL,
APELLIDO_PATERNO VARCHAR2(30) CONSTRAINT CLIENTE_APPATERNO_NN NOT NULL,
APELLIDO_MATERNO VARCHAR2(30) CONSTRAINT CLIENTE_APMATERNO_NN NOT NULL,
COLONIA VARCHAR2(30) CONSTRAINT EMPLEADO_COL_NN NOT NULL,
CALLE VARCHAR2(30),
CONSTRAINT CLIENTE_TEL_UK UNIQUE(TELEFONO)
);

CREATE TABLE HABITACION(
ID_HABITACION NUMBER(15) CONSTRAINT HABITACION_PK PRIMARY KEY,
NOMBRE VARCHAR(30) CONSTRAINT HABITACION_NOM_NN NOT NULL,
ID_TIPO NUMBER(3) CONSTRAINT HABITACION_TIPO_NN NOT NULL,
CONSTRAINT HABITACION_TIPO_FK FOREIGN KEY (ID_TIPO) REFERENCES TIPO_HABITACION(ID_TIPO)
);

CREATE TABLE HOTEL(
ID_HOTEL NUMBER(6) CONSTRAINT HOTEL_PK PRIMARY KEY,
NOMBRE VARCHAR(30) CONSTRAINT HOTEL_NOM_NN NOT NULL,
TELEFONO VARCHAR2(20) CONSTRAINT HOTEL_TEL_NN NOT NULL,
FECHA_CONSTRUCCION DATE CONSTRAINT HOTEL_FECHA_NN NOT NULL,
COLONIA VARCHAR2(30) CONSTRAINT HOTEL_COL_NN NOT NULL,
CALLE VARCHAR2(30),
ID_CATEGORIA NUMBER(3) CONSTRAINT HOTEL_CATEGORIA_NN NOT NULL,
CONSTRAINT HOTEL_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);



CREATE TABLE HABITACION_HOTEL(
ID_HABITACION_HOTEL NUMBER(15) CONSTRAINT HABITACION_HOTEL_PK PRIMARY KEY,
ID_HABITACION NUMBER(15),
ID_HOTEL NUMBER(6),
CANTIDAD NUMBER(3) CONSTRAINT HABITACION_HOTEL_CANTIDAD_NN NOT NULL,
CONSTRAINT HAB_HOTEL_HABITACION_FK FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION),
CONSTRAINT HAB_HOTEL_HOTEL_FK FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);

CREATE TABLE RESERVA(
ID_RESERVA NUMBER(15) CONSTRAINT RESERVA_PK PRIMARY KEY,
ID_EMPLEADO_AGENCIA NUMBER(10),
ID_CLIENTE NUMBER(10),
ID_HABITACION_HOTEL NUMBER(15),
FECHA_INICIO DATE CONSTRAINT RESERVA_FECHA_INICIO_NN NOT NULL,
FECHA_FIN DATE CONSTRAINT RESERVA_FECHA_FIN_NN NOT NULL,
PRECIO NUMBER(9, 2) CONSTRAINT RESERVA_PRECIO_NN NOT NULL,
CONSTRAINT RESERVA_PRECIO_CH CHECK (PRECIO > 100),
CONSTRAINT RESERVA_AG_EMP_FK FOREIGN KEY (ID_EMPLEADO_AGENCIA) REFERENCES EMPLEADO_AGENCIA(ID_EMPLEADO_AGENCIA),
CONSTRAINT RESERVA_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT RESERVA_HAB_HOTEL_FK FOREIGN KEY (ID_HABITACION_HOTEL) REFERENCES HABITACION_HOTEL(ID_HABITACION_HOTEL)
);

