
CREATE TABLE DEPT0 (
ID NUMBER(7,0) PRIMARY KEY,
NAME VARCHAR2(25) CONSTRAINT DEPT_NAME_NN NOT NULL
);

CREATE TABLE DEPT (
ID,
NAME
) AS SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM HR.DEPARTMENTS;

ALTER TABLE DEPT ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (ID);


