CREATE TABLE EMP (
ID NUMBER(7),
LAST_NAME varchar2(25),
FIRST_NAME varchar2(25),
DEPT_ID NUMBER(7),
CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID)
);

CREATE TABLE EMPLOYEES2 (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID)
AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM HR.EMPLOYEES;


ALTER TABLE EMPLOYEES2 READ ONLY;

INSERT INTO employees2 (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID) VALUES (34, 'Grant', 'Marcie', 5678, 10);

ALTER TABLE EMPLOYEES2 READ write;

INSERT INTO employees2 (ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_ID) VALUES (34, 'Grant', 'Marcie', 5678, 10);

DROP TABLE EMPLOYEES2;
PURGE TABLE EMPLOYEES2;
