CREATE OR REPLACE VIEW EMPLOYEES_VU AS SELECT EMPLOYEE_ID, LAST_NAME EMPLOYEE, DEPARTMENT_ID FROM EMPLOYEES;
SELECT * FROM HR.EMPLOYEES_VU;

CREATE OR REPLACE VIEW DEPT50 AS SELECT EMPLOYEE_ID EMPNO, LAST_NAME EMPLOYEE, DEPARTMENT_ID DEPTNO FROM EMPLOYEES WHERE DEPARTMENT_ID=50 WITH READ ONLY;
DESCRIBE DEPT50;
SELECT * FROM HR.DEPT50;

UPDATE DEPT50 SET DEPTNO=80 WHERE EMPNO=143;

CREATE SEQUENCE DEPT_ID_SEQ START WITH 200 INCREMENT BY 10 MAXVALUE 1000;
CREATE UNIQUE INDEX DEPT_ID_INDEX ON DEPT(EMPLOYEE);

CREATE SYNONYM EMP FOR EMPLOYEES;

CREATE SYNONYM DEPT FOR DEPARTMENTS;
