SELECT LAST_NAME, LENGTH(LAST_NAME) FROM HR.employees WHERE LAST_NAME LIKE 'A%' OR LAST_NAME LIKE 'J%' OR LAST_NAME LIKE 'M%';


SELECT LAST_NAME, LENGTH(LAST_NAME) FROM HR.employees WHERE LAST_NAME LIKE UPPER('&letra')||'%';