-- a) = y <>
SELECT * FROM HOTEL WHERE ID_HOTEL <> 1;
SELECT * FROM HOTEL WHERE ID_HOTEL = 1;
SELECT * FROM HOTEL WHERE COLONIA = 'Santa María';

--b) > y <
SELECT * FROM HOTEL WHERE fecha_construccion > TO_DATE('05/12/14');
SELECT * FROM HOTEL WHERE ID_HOTEL > 1 AND ID_HOTEL < 5;
SELECT * FROM HOTEL WHERE COLONIA > 'Comox';

--c) >= y <=
SELECT * FROM HOTEL WHERE fecha_construccion >= TO_DATE('05/12/14');
SELECT * FROM HOTEL WHERE ID_HOTEL >= 1 AND ID_HOTEL <= 1;
SELECT * FROM HOTEL WHERE ID_HOTEL <= 3 OR ID_HOTEL >= 5;

--d) Between y not between
SELECT * FROM HOTEL WHERE fecha_construccion >= TO_DATE('05/12/14');

--e) In y not in
SELECT * FROM EMPLEADO WHERE TELEFONO IN ('16830418 9379', '16590823 7919', '16811118 7483');
SELECT * FROM EMPLEADO WHERE TELEFONO NOT IN ('16830418 9379', '16590823 7919', '16811118 7483');
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO NOT IN (6,5,4);

--f) Like y not like
SELECT * FROM EMPLEADO WHERE TELEFONO IN ('16830418 9379', '16590823 7919', '16811118 7483');
SELECT * FROM EMPLEADO WHERE TELEFONO NOT IN ('16830418 9379', '16590823 7919', '16811118 7483');
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO NOT IN (6,5,4);

--g) Like y not like (ESCAPE)
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '__a%' ESCAPE '\';
SELECT * FROM EMPLEADO WHERE TELEFONO NOT LIKE '%111%' ESCAPE '\';
SELECT * FROM EMPLEADO WHERE TELEFONO LIKE '%111%' ESCAPE '\';

--h) Is null e is not null
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NULL;
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NOT NULL;
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NULL AND IVA IS NOT NULL;

--i) And
SELECT * FROM HABITACION WHERE ID_HABITACION > 1 AND ID_HABITACION < 5;
SELECT * FROM HABITACION WHERE ID_HABITACION >= 1 AND ID_HABITACION <= 1;
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NULL AND IVA IS NOT NULL;

--j) Or
SELECT * FROM HOTEL WHERE ID_HOTEL < 3 OR ID_HOTEL >= 5;
SELECT * FROM HABITACION WHERE ID_HABITACION <= 1 OR ID_HABITACION >= 4;
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NULL OR IVA IS NOT NULL;

--k) Uso de paréntesis
SELECT * FROM HOTEL WHERE (ID_HOTEL < 3 OR ID_HOTEL >= 5) AND DESCRIPCION IS NULL;
SELECT * FROM HABITACION WHERE (TELEFONO NOT LIKE '%111%' ESCAPE '\' AND ID_HABITACION <= 1) OR ID_HABITACION >= 4;
SELECT * FROM CATEGORIA WHERE DESCRIPCION IS NULL OR (IVA IS NOT NULL AND TELEFONO IN ('16830418 9379', '16590823 7919', '16811118 7483'));

--l) Precedencia de operadores
SELECT * FROM HABITACION WHERE ID_HABITACION > 1+1 AND ID_HABITACION < 5;
SELECT * FROM HABITACION WHERE ID_HABITACION >= 1+1 AND ID_HABITACION <= 1;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN (6 + 4,5 * 3,4 / 2);

--m) Order by
SELECT * FROM HOTEL WHERE fecha_construccion > TO_DATE('05/12/14') ORDER BY fecha_construccion, ID_HOTEL;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO NOT IN (6,5,4) ORDER BY ID_EMPLEADO ASC;
SELECT TELEFONO FROM EMPLEADO WHERE TELEFONO NOT LIKE '%111%' ESCAPE '\' ORDER BY TELEFONO DESC;

--n) Variables de sustitución con &
SELECT * FROM HOTEL WHERE COLONIA LIKE '&PRIMERA_PALABRA%';
SELECT * FROM HOTEL WHERE COLONIA LIKE '&PRIMERA_LETRA%';
SELECT * FROM HOTEL WHERE COLONIA LIKE '__&TERCERA_LETRA%';

--o) Variables de sustitución con &&
SELECT &&COLUMNA FROM EMPLEADO WHERE &&COLUMNA LIKE '%111%' ESCAPE '\' ORDER BY &&COLUMNA DESC;
SELECT * FROM HOTEL WHERE ID_HOTEL = &&ID;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = &&ID;

--p) Define
DEFINE MIN_ID = 3;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO >= &MIN_ID;
DEFINE TEL = '16830418 9379';
SELECT * FROM EMPLEADO WHERE TELEFONO LIKE '&TEL';
DEFINE MAX_ID = 5;
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO >= &MIN_ID AND ID_EMPLEADO <= &MAX_ID;
UNDEFINE MIN_ID;
UNDEFINE MAX_ID;
UNDEFINE TEL;