SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT BETWEEN 0.1 AND 0.5;

SELECT * FROM HR.EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT * FROM HR.EMPLOYEES WHERE NOT(COMMISSION_PCT IS NOT NULL);



SELECT * FROM HR.EMPLOYEES WHERE SALARY >=2000 AND <=5000;
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'R%'
ORDER BY 3 DESC NULLS LAST, 2 ASC;


DEFINE TAX_RATE=0.14
SELECT SALARY * :TAX_RATE TAX FROM EMPLOYEES;
SELECT SALARY, SALARY * &TAX_RATE TAX FROM EMPLOYEES;
SELECT SALARY * :&&TAX TAX FROM EMPLOYEES;
SELECT SALARY * TAX_RATE TAX FROM EMPLOYEES;

UNDEFINE JOB;

SELECT FIRST_NAME, '&JOB'
FROM EMPLOYEES
WHERE JOB_ID LIKE '%'||&JOB||'%'
AND '&&JOB' BETWEEN 'A' AND 'Z';
