INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'adipiscing,');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'et nunc.');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'varius orci, in');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'cursus');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'nostra, per inceptos hymenaeos.');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'auctor, velit');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'vestibulum, neque');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'Aliquam rutrum lorem ac risus.');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'arcu. Vestibulum');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'dui. Fusce diam nunc, ullamcorper');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'laoreet lectus quis');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'ipsum cursus');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'nisi. Cum sociis natoque');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'ornare.');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'hymenaeos. Mauris ut quam vel');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'egestas, urna justo faucibus');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'orci');
INSERT INTO TIPO_HABITACION (ID_TIPO,DESCRIPCION) VALUES (TIPO_HABITACION_SEQ_ID.NEXTVAL,'Class aptent taciti sociosqu');


-- CATEGORIA

INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'nunc sit amet metus. Aliquam',95);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'cursus et, eros. Proin ultrices.',83);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'in felis. Nulla',94);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'sodales. Mauris blandit',99);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'ipsum nunc id enim. Curabitur',51);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'dictum magna. Ut',53);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'diam dictum sapien.',94);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'Suspendisse tristique neque',42);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'et netus et',39);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'nec enim. Nunc ut erat.',78);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'vel lectus. Cum',30);
INSERT INTO CATEGORIA (ID_CATEGORIA,DESCRIPCION,IVA) VALUES (CATEGORIA_SEQ_ID.NEXTVAL,'Quisque fringilla euismod enim. Etiam gravida',55);


-- AGENCIA

INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16700720 6605','Rana','Haasdonk','6863 Orci St.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16090403 6670','Felicia','Tuluá','802-2857 Faucibus Rd.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16450320 3921','Luke','Inuvik','5514 Ullamcorper. Rd.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16210604 4023','Cherokee','Bellevue','4535 Donec Rd.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16060612 5334','Miriam','Höchst','P.O. Box 286, 1589 Ultrices. Avenue');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16190225 2194','Quail','La Hulpe','9098 Tortor St.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16890418 6858','Thane','Mirzapur-cum-Vindhyachal','7311 Non Ave');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16510305 2121','Kim','Blenheim','P.O. Box 440, 3806 Duis Av.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16431019 8397','Mollie','Puerto Colombia','Ap #128-4797 Maecenas Avenue');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16991103 1442','Kylie','Hilo','Ap #887-8064 Urna, Rd.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16610522 9642','Kylan','WanfercŽe-Baulet','P.O. Box 688, 5138 Metus St.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16710728 6796','Charlotte','Saint-Quentin','272-1062 Nunc. Ave');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16121012 1511','Angelica','Sherbrooke','820-9073 At St.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16680511 9481','Wallace','Gyeongju','567-7394 Sed St.');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16040821 7487','Lael','Rocca d''Arce','189-1160 Metus. Avenue');
INSERT INTO AGENCIA (ID_AGENCIA,TELEFONO,NOMBRE,COLONIA,CALLE) VALUES (AGENCIA_SEQ_ID.NEXTVAL,'16871130 4959','Miranda','Caplan','Ap #414-1614 Sem St.');

-- EMPLEADO

INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16120121 3434','Camden','Conley','Serrano');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16241002 9520','Ori','Dodson','Macdonald');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16850222 7989','Kirsten','Brady','Hull');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16390812 2405','Travis','Turner','Horn');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16681109 2003','Erin','Reed','Mendez');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16710303 3788','Maisie','Mason','Carson');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16551203 4736','Graham','Mckinney','Brennan');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16950601 3862','Tashya','Rich','Hurley');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16891128 0017','Mariko','Durham','Terrell');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16510314 3458','Ainsley','Flores','Hicks');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16660208 0936','Wyoming','Snider','Gentry');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16640529 5475','Danielle','Mills','Harvey');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16871018 3867','Isaac','Silva','Hawkins');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16491115 8311','Alana','Dean','Haley');
INSERT INTO EMPLEADO (ID_EMPLEADO,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO) VALUES (EMPLEADO_SEQ_ID.NEXTVAL,'16920615 9403','Constance','Stephenson','Key');


-- EMPLEADO_AGENCIA
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,5,3);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,1,2);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,4,6);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,4,2);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,3,8);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,5,7);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,2,9);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,1,7);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,6,6);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,1,6);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,8,7);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,10,1);
INSERT INTO EMPLEADO_AGENCIA (ID_EMPLEADO_AGENCIA,ID_EMPLEADO,ID_AGENCIA) VALUES (EMPLEADO_AGENCIA_SEQ_ID.NEXTVAL,2,9);


INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16010820 6491','Hamilton','Dickerson','West','Gto','P.O. Box 514, 441 Mi. Street');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16200712 2506','Cruz','Mcknight','Dudley','Mic','273-4105 Tristique Rd.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16160820 3186','Jerome','Zamora','Mccarthy','Son','2508 Ullamcorper St.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16940927 9495','Riley','Gilbert','Shields','Tam','900-5623 Turpis. St.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16871029 7568','Riley','Barber','Gibson','Hgo','Ap #688-6198 Fermentum St.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16310909 3132','Colin','Cote','Key','Mic','Ap #600-4976 Et, Rd.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16500324 7342','Joshua','Norton','Cannon','Tam','484-4296 Nunc Road');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16790512 6244','Neil','Stein','Barber','Oax','1175 Nulla St.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16270430 7848','Daniel','Holmes','Joyce','Gto','8558 Mi. Rd.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16690320 9150','Judah','Todd','Mosley','Mic','Ap #598-7273 Mus. Street');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16361226 6159','Acton','Serrano','Conley','Ver','P.O. Box 719, 1300 Ligula. Rd.');
INSERT INTO CLIENTE (ID_CLIENTE,TELEFONO,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,COLONIA,CALLE) VALUES (CLIENTE_SEQ_ID.NEXTVAL,'16401213 0490','Rooney','Serrano','Ortiz','Qro','324-5928 Sit Road');


INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Versailles',5);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Karak',6);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Pushkino',1);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Patos',6);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Dresden',5);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Tailles',4);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'College',2);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Sobral',8);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Guarapuava',10);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Tirupati',8);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Gloucester',4);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Fayetteville',8);
INSERT INTO HABITACION (ID_HABITACION,NOMBRE,ID_TIPO) VALUES (HABITACION_SEQ_ID.NEXTVAL,'Westmount',9);


--delete from HOTEL;

INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Minatitlán','20333287299','01/07/1994','Veracruz','P.O. Box 239, 1627 Magna. Street',7);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Zamora de Hidalgo','58776151999','18/08/2016','Michoacán','4571 Nam Ave',6);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Tampico','58771007499','30/04/1991','Tamaulipas','421-3176 Etiam Street',8);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Tehuacán','61385495599','02/04/2009','Puebla','854-2098 Fames St.',2);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'General Escobedo','89747834699','21/06/2017','Nuevo León','3559 Vitae Av.',8);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Tehuacán','44440799199','06/03/2002','Puebla','221-7381 Elit, Road',4);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Ensenada','35403478999','27/09/2003','Baja California','Ap #149-9796 Non Rd.',5);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Orizaba','71686216099','06/02/2006','Veracruz','Ap #176-1860 Justo. Road',4);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Zamora de Hidalgo','59464563699','25/05/1995','Michoacán','P.O. Box 347, 2497 Volutpat Road',1);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'La Paz','49375570399','30/11/2001','Baja California','P.O. Box 511, 9013 Egestas Street',7);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Puerto Vallarta','05299534099','11/07/1993','Jalisco','Ap #212-7545 Dolor, Ave',3);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Oaxaca','25537757799','12/12/1997','Oaxaca','Ap #545-6732 Non Avenue',10);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Villahermosa','50354207899','04/12/2012','Tabasco','P.O. Box 293, 8575 Sed Ave',2);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'Villahermosa','68863055399','03/05/2008','Tabasco','7881 Nibh St.',1);
INSERT INTO HOTEL (ID_HOTEL,NOMBRE,TELEFONO,FECHA_CONSTRUCCION,COLONIA,CALLE,ID_CATEGORIA) VALUES (HOTEL_SEQ_ID.NEXTVAL,'León','15839741599','26/10/2002','Guanajuato','Ap #125-5284 Neque Road',5);



INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,10,10,92);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,6,2,60);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,8,2,88);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,1,1,68);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,1,7,46);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,3,4,41);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,1,8,91);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,4,3,65);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,5,2,27);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,6,6,21);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,8,2,44);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,9,3,60);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,2,2,18);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,7,1,49);
INSERT INTO HABITACION_HOTEL (ID_HABITACION_HOTEL,ID_HABITACION,ID_HOTEL,CANTIDAD) VALUES (HABITACION_HOTEL_SEQ_ID.NEXTVAL,5,10,48);



INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,9,3,10,'07/12/2008','10/09/2015','2512.82');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,4,4,2,'09/10/2011','15/09/2016','5271.62');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,10,9,3,'28/01/2010','13/08/2019','8227.58');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,4,8,8,'07/10/2004','30/07/2016','4208.85');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,7,2,8,'06/11/2005','01/11/2015','4303.39');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,6,9,2,'08/10/2005','10/02/2021','7926.25');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,8,4,9,'25/12/2010','10/11/2013','1229.56');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,4,10,8,'24/04/2008','16/03/2016','9460.05');
INSERT INTO RESERVA (ID_RESERVA,ID_EMPLEADO_AGENCIA,ID_CLIENTE,ID_HABITACION_HOTEL,FECHA_INICIO,FECHA_FIN,PRECIO) VALUES (RESERVA_SEQ_ID.NEXTVAL,9,9,2,'23/11/2007','16/08/2019','1649.98');













