--SELECT * FROM HR.REGIONS;
--DESCRIBE HR.REGIONS;


--DROP TABLE DEPARTAMENTOS_LEOR;
--PURGE TABLE DEPARTAMENTOS_LEOR;
--DROP TABLE EMPLEADOS_LEOR;
--PURGE TABLE EMPLEADOS_LEOR;
--DROP TABLE UBICACIONES_LEOR;
--PURGE TABLE UBICACIONES_LEOR;
--DROP TABLE PAISES_LEOR;
--PURGE TABLE PAISES_LEOR;
--DROP TABLE REGIONES_LEOR;
--PURGE TABLE REGIONES_LEOR;
--DROP TABLE PUESTOS_LEOR;
--PURGE TABLE PUESTOS_LEOR;


CREATE TABLE REGIONES_LEOR(
ID_REGION NUMBER CONSTRAINT REGIONES_ID_PK PRIMARY KEY,
NOMBRE_REGION VARCHAR2(25) CONSTRAINT REGIONES_NOM_NN NOT NULL
);

INSERT INTO REGIONES_LEOR(ID_REGION, NOMBRE_REGION)
    (SELECT REGION_ID, REGION_NAME FROM HR.REGIONS);




CREATE TABLE PAISES_LEOR(
ID_PAIS CHAR(2) CONSTRAINT PAISES_ID_PK PRIMARY KEY,
NOMBRE_PAIS VARCHAR2(40),
ID_REGION NUMBER,
CONSTRAINT PAISES_REG_FK FOREIGN KEY (ID_REGION) REFERENCES REGIONES_LEOR(ID_REGION)
);

INSERT INTO PAISES_LEOR(ID_PAIS, NOMBRE_PAIS, ID_REGION)
    (SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID FROM HR.COUNTRIES);




CREATE TABLE UBICACIONES_LEOR(
ID_UBICACION NUMBER(4,0) CONSTRAINT UBICACIONES_ID_PK PRIMARY KEY,
DIRECCION VARCHAR2(40),
CODIGO_POSTAL VARCHAR2(12),
CIUDAD VARCHAR2(30) CONSTRAINT UBICACIONES_CIUDAD_NN NOT NULL,
ESTADO VARCHAR2(25),
ID_PAIS CHAR(2),
CONSTRAINT UBICACIONES_PAISES_FK FOREIGN KEY (ID_PAIS) REFERENCES PAISES_LEOR(ID_PAIS)
);

INSERT INTO UBICACIONES_LEOR(ID_UBICACION, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO, ID_PAIS)
    (SELECT LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID FROM HR.LOCATIONS);




CREATE TABLE PUESTOS_LEOR(
ID_PUESTO VARCHAR2(10) CONSTRAINT PUESTOS_ID_PK PRIMARY KEY,
TITULO_PUESTO VARCHAR2(35) CONSTRAINT PUESTOS_TITULO_NN NOT NULL,
SALARIO_MIN NUMBER(6,0),
SALARIO_MAX NUMBER(6,0)
);

INSERT INTO PUESTOS_LEOR(ID_PUESTO, TITULO_PUESTO, SALARIO_MIN, SALARIO_MAX)
    (SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM HR.JOBS);





CREATE TABLE DEPARTAMENTOS_LEOR(
ID_DEPARTAMENTO NUMBER(4,0) CONSTRAINT DEPARTAMENTO_ID_PK PRIMARY KEY,
NOMBRE_DEPARTAMENTO VARCHAR2(30) CONSTRAINT DEPARTAMENTO_NOMBRE_NN NOT NULL,
ID_GERENTE NUMBER(6,0),
ID_UBICACION NUMBER(6,0),
CONSTRAINT DEPARTAMENTO_UBIC_FK FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES_LEOR(ID_UBICACION)
);







CREATE TABLE EMPLEADOS_LEOR(
ID_EMPLEADO NUMBER(6,0) CONSTRAINT EMPLEADOS_ID_PK PRIMARY KEY,
NOMBRE VARCHAR2(20),
APELLIDO VARCHAR2(25) CONSTRAINT EMPLEADOS_APELLIDO_NN NOT NULL,
CORREO VARCHAR2(25) CONSTRAINT EMPLEADOS_CORREO_NN NOT NULL,
TELEFONO VARCHAR2(20),
FECHA_CONTRATACION DATE CONSTRAINT EMPLEADOS_FECHA_NN NOT NULL,
ID_PUESTO VARCHAR2(10) CONSTRAINT EMPLEADOS_PUESTO_NN NOT NULL,
ID_GERENTE NUMBER(6,0),
ID_DEPARTAMENTO NUMBER(4,0),
SALARIO NUMBER(8,2) CONSTRAINT EMPLEADOS_SALARIO_MIN CHECK (SALARIO > 0),
COMISION NUMBER(2,2),
CONSTRAINT EMPLEADOS_CORREO_U UNIQUE (CORREO),
CONSTRAINT EMPLEADOS_PUESTOS_FK FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS_LEOR(ID_PUESTO),
CONSTRAINT EMPLEADOS_EMP_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADOS_LEOR(ID_EMPLEADO)
);


INSERT INTO EMPLEADOS_LEOR(ID_EMPLEADO, NOMBRE, APELLIDO, CORREO, TELEFONO, FECHA_CONTRATACION, ID_PUESTO, ID_GERENTE, ID_DEPARTAMENTO, SALARIO, COMISION)
    (SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, MANAGER_ID, DEPARTMENT_ID, SALARY, COMMISSION_PCT FROM HR.EMPLOYEES);



INSERT INTO DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ID_GERENTE, ID_UBICACION)
    (SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID FROM HR.DEPARTMENTS);


ALTER TABLE DEPARTAMENTOS_LEOR ADD CONSTRAINT DEPARTAMENTOS_EMP_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADOS_LEOR(ID_EMPLEADO);
ALTER TABLE EMPLEADOS_LEOR ADD CONSTRAINT EMPLEADOS_DEPT_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO);



CREATE TABLE HISTORIAL_PUESTOS_LEOR(
ID_EMPLEADO NUMBER(6,0) CONSTRAINT HISTORIAL_ID_EMPLEADO_NN NOT NULL,
FECHA_INICIO DATE CONSTRAINT HISTORIAL_FECHA_INICIO_NN NOT NULL,
FECHA_FIN DATE CONSTRAINT HISTORIAL_FECHA_FIN_NN NOT NULL,
ID_PUESTO VARCHAR2(10) CONSTRAINT HISTORIAL_PUESTO_NN NOT NULL,
ID_DEPARTAMENTO NUMBER(4,0),
CONSTRAINT HISTORIAL_INTERVALO_FECHA_CH CHECK (FECHA_FIN > FECHA_INICIO),
CONSTRAINT HISTORIAL_PUESTOS_FK FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS_LEOR(ID_PUESTO),
CONSTRAINT HISTORIAL_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS_LEOR(ID_EMPLEADO),
CONSTRAINT HISTORIAL_DEP_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO),
CONSTRAINT HISTORIAL_PK PRIMARY KEY (ID_EMPLEADO, FECHA_INICIO)
);



INSERT INTO HISTORIAL_PUESTOS_LEOR(ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, ID_PUESTO, ID_DEPARTAMENTO)
    (SELECT EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID FROM HR.JOB_HISTORY);
