
ALTER TABLE DEPARTAMENTOS_LEOR REMOVE CONSTRAINT DEPARTAMENTOS_EMP_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADOS_LEOR(ID_EMPLEADO);
ALTER TABLE EMPLEADOS_LEOR ADD CONSTRAINT EMPLEADOS_DEPT_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO);

TRUNCATE TABLE HISTORIAL_PUESTOS_LEOR;
TRUNCATE TABLE DEPARTAMENTOS_LEOR;
TRUNCATE TABLE EMPLEADOS_LEOR;
TRUNCATE TABLE UBICACIONES_LEOR;
TRUNCATE TABLE PAISES_LEOR;
TRUNCATE TABLE REGIONES_LEOR;
TRUNCATE TABLE PUESTOS_LEOR;

INSERT INTO REGIONES_LEOR(ID_REGION, NOMBRE_REGION)
    (SELECT REGION_ID, REGION_NAME FROM HR.REGIONS);


SELECT SEQ_REG_PK.CURVAL FROM DUAL;
INSERT INTO REGIONES_LEOR VALUES (SEQ_REG_PK.NEXTVAL, 'Artico');
INSERT INTO REGIONES_LEOR VALUES (SEQ_REG_PK.NEXTVAL, 'Antartida');
INSERT INTO REGIONES_LEOR VALUES (SEQ_REG_PK.NEXTVAL, 'Atlantico');
INSERT INTO REGIONES_LEOR VALUES (SEQ_REG_PK.NEXTVAL, 'Oceania');
INSERT INTO REGIONES_LEOR VALUES (SEQ_REG_PK.NEXTVAL, 'Latino-America');


INSERT INTO PAISES_LEOR(ID_PAIS, NOMBRE_PAIS, ID_REGION)
    (SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID FROM HR.COUNTRIES);

INSERT INTO PAISES_LEOR VALUES ('CU', 'CUBA', 9);
INSERT INTO PAISES_LEOR VALUES ('CO', 'Colombia', 9);
INSERT INTO PAISES_LEOR VALUES ('VZ', 'Venezuela', 9);
INSERT INTO PAISES_LEOR VALUES ('CL', 'CHILE', 9);
INSERT INTO PAISES_LEOR VALUES ('PT', 'Portugal', 1);




INSERT INTO UBICACIONES_LEOR(ID_UBICACION, DIRECCION, CODIGO_POSTAL, CIUDAD, ESTADO, ID_PAIS)
    (SELECT LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID FROM HR.LOCATIONS);


INSERT INTO UBICACIONES_LEOR VALUES (SEQ_UBIC_PK.NEXTVAL, '12 Agustin Melgar', '65243', 'El Alamo', 'Palamarito', 'CU');
INSERT INTO UBICACIONES_LEOR VALUES (SEQ_UBIC_PK.NEXTVAL, '1 Melchor', '82625', 'Cascaza', 'Feca', 'CO');
INSERT INTO UBICACIONES_LEOR VALUES (SEQ_UBIC_PK.NEXTVAL, '5000 Via la cruz', '13863', 'Cicala', 'Caracas', 'VZ');
INSERT INTO UBICACIONES_LEOR VALUES (SEQ_UBIC_PK.NEXTVAL, '305', '72535', 'Balderas', 'Xotil', 'CL');
INSERT INTO UBICACIONES_LEOR VALUES (SEQ_UBIC_PK.NEXTVAL, '201 Ortegas', '98265', 'Dimas', 'Shuba', 'PT');




INSERT INTO PUESTOS_LEOR(ID_PUESTO, TITULO_PUESTO, SALARIO_MIN, SALARIO_MAX)
    (SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM HR.JOBS);

SELECT * FROM PUESTOS_LEOR;
INSERT INTO PUESTOS_LEOR VALUES ('IT_IS', 'Ingeniero de Software', 5000, 100000);
INSERT INTO PUESTOS_LEOR VALUES ('IT_CO', 'El de las copias', 100, 500);
INSERT INTO PUESTOS_LEOR VALUES ('CL_BR', 'LIMPIEZA', 5000, 100000);
INSERT INTO PUESTOS_LEOR VALUES ('IT_IS', 'Ingeniero de Software', 5000, 100000);
INSERT INTO PUESTOS_LEOR VALUES ('IT_IS', 'Ingeniero de Software', 5000, 100000);





INSERT INTO EMPLEADOS_LEOR(ID_EMPLEADO, NOMBRE, APELLIDO, CORREO, TELEFONO, FECHA_CONTRATACION, ID_PUESTO, ID_GERENTE, ID_DEPARTAMENTO, SALARIO, COMISION)
    (SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, MANAGER_ID, DEPARTMENT_ID, SALARY, COMMISSION_PCT FROM HR.EMPLOYEES);



INSERT INTO DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ID_GERENTE, ID_UBICACION)
    (SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID FROM HR.DEPARTMENTS);

/*
ALTER TABLE DEPARTAMENTOS_LEOR ADD CONSTRAINT DEPARTAMENTOS_EMP_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADOS_LEOR(ID_EMPLEADO);
ALTER TABLE EMPLEADOS_LEOR ADD CONSTRAINT EMPLEADOS_DEPT_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS_LEOR(ID_DEPARTAMENTO);


*/

INSERT INTO HISTORIAL_PUESTOS_LEOR(ID_EMPLEADO, FECHA_INICIO, FECHA_FIN, ID_PUESTO, ID_DEPARTAMENTO)
    (SELECT EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID FROM HR.JOB_HISTORY);
