/*
SIEMPRE USAR MATUSCULAS EN USUARIO Y PASSWORD
*/
DEFINE usuario = 'RH';
--DROP USER "luis1" CASCADE;

CREATE USER "&usuario" IDENTIFIED BY "ORACLE"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
PROFILE default ACCOUNT UNLOCK;

GRANT CONNECT TO "&usuario";
GRANT CREATE SESSION TO "&usuario";
GRANT UNLIMITED TABLESPACE TO "&usuario";

--GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO "&usuario";

GRANT ALTER ANY INDEX TO "&usuario";
GRANT DROP ANY SEQUENCE TO "&usuario";
GRANT DROP ROLLBACK SEGMENT TO "&usuario";
GRANT ALTER SESSION TO "&usuario";
GRANT CREATE ANY INDEX TO "&usuario";
GRANT CREATE ANY SEQUENCE TO "&usuario";
GRANT CREATE VIEW TO "&usuario";
GRANT ALTER ANY TABLE TO "&usuario";
GRANT CREATE SESSION TO "&usuario";
GRANT SELECT ANY TABLE TO "&usuario";
GRANT DELETE ANY TABLE TO "&usuario";
GRANT ALTER ANY SEQUENCE TO "&usuario";
GRANT CREATE TABLE TO "&usuario";
GRANT DROP ANY TABLE TO "&usuario";
GRANT SELECT ANY SEQUENCE TO "&usuario";
GRANT CREATE ROLLBACK SEGMENT TO "&usuario";
GRANT CREATE PUBLIC SYNONYM TO "&usuario";
GRANT CREATE ANY SYNONYM TO "&usuario";
GRANT DROP ANY SYNONYM TO "&usuario";
GRANT CREATE SYNONYM TO "&usuario";
GRANT CREATE SEQUENCE TO "&usuario";
GRANT DROP ANY INDEX TO "&usuario";
GRANT CREATE USER TO "&usuario";
GRANT UPDATE ANY TABLE TO "&usuario";
GRANT DROP ANY VIEW TO "&usuario";
GRANT CREATE ANY VIEW TO "&usuario";
GRANT DROP PUBLIC SYNONYM TO "&usuario";
GRANT INSERT ANY TABLE TO "&usuario";
GRANT CREATE ANY TABLE TO "&usuario";
GRANT DROP TABLESPACE TO "&usuario";

COMMIT;