CREATE OR REPLACE VIEW EMPLOYEES_VU AS SELECT EMPLOYEE_ID, LAST_NAME EMPLOYEE, DEPARTMENT_ID FROM EMPLOYEES;
SELECT * FROM HR.EMPLOYEES_VU;

CREATE OR REPLACE VIEW DEPT50 AS SELECT EMPLOYEE_ID EMPNO, LAST_NAME EMPLOYEE, DEPARTMENT_ID DEPTNO FROM EMPLOYEES WHERE DEPARTMENT_ID=50 WITH READ ONLY;
DESCRIBE DEPT50;
SELECT * FROM HR.DEPT50;

UPDATE DEPT50 SET DEPTNO=80 WHERE EMPNO=143;

CREATE SEQUENCE DEPT_ID_SEQ START WITH 200 INCREMENT BY 10 MAXVALUE 1000;
CREATE UNIQUE INDEX DEPT_ID_INDEX ON DEPT(EMPLOYEE);

CREATE SYNONYM EMP FOR EMPLOYEES;

CREATE SYNONYM DEPT FOR DEPARTMENTS;




/**
 * Ejercicio 3
 */
 
DROP TABLE CHANNEL;
DROP TABLE M_DATE;
DROP TABLE SHOP;
DROP TABLE PRODUCT;

CREATE TABLE SHOP (
SHOP_ID NUMBER(2) CONSTRAINT SHOP_ID_PK PRIMARY KEY,
ADDRESS VARCHAR2(100) CONSTRAINT SHOP_ADDRESS_NN NOT NULL
);

CREATE TABLE M_DATE (
DAY_ID NUMBER(3) CONSTRAINT DAY_ID_PK PRIMARY KEY,
M_DATE DATE CONSTRAINT DATE_NN NOT NULL
);

CREATE TABLE CHANNEL (
CHANNEL_ID NUMBER(2) CONSTRAINT CHANNEL_ID_PK PRIMARY KEY,
CNAME VARCHAR2(25) CONSTRAINT CNAME_NN NOT NULL
);

CREATE TABLE PRODUCT (
PRODUCT_ID NUMBER(3) CONSTRAINT PROD_ID_PK PRIMARY KEY,
PNAME VARCHAR2(50) CONSTRAINT PROD_PNAME_U UNIQUE,
PRICE NUMBER(7, 2) CONSTRAINT PROD_PRICE_NN NOT NULL
);

CREATE TABLE SALE(
SALE_ID NUMBER(20) CONSTRAINT SALE_ID_PK PRIMARY KEY,
QUANTITY NUMBER(4) CONSTRAINT SALE_QUANTITY_CH CHECK(QUANTITY > 0),
CHANNEL_ID NUMBER(2) CONSTRAINT CHANNEL_FK REFERENCES CHANNEL(CHANNEL_ID),
PRODUCT_ID NUMBER(3) CONSTRAINT PRODUCT_FK REFERENCES PRODUCT(PRODUCT_ID),
SHOP_ID NUMBER(2) CONSTRAINT SHOP_FK REFERENCES SHOP(SHOP_ID),
DAY_ID NUMBER(3) CONSTRAINT DAY_FK REFERENCES M_DATE(DAY_ID)
);


CREATE SEQUENCE SHOP_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100;
CREATE SEQUENCE M_DATE_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 365;
CREATE SEQUENCE CHANNEL_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100;
CREATE SEQUENCE PRODUCT_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 1000;
CREATE SEQUENCE SALE_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 10000000000000000000;


CREATE SYNONYM SH FOR SHOP;
CREATE SYNONYM D FOR M_DATE;
CREATE SYNONYM P FOR PRODUCT;
CREATE SYNONYM C FOR CHANNEL;
CREATE SYNONYM SL FOR SALE;




/**
 * Ejercicio 4
 */


CREATE SEQUENCE TIPO_HABITACION_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100;
CREATE SEQUENCE CATEGORIA_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100;
CREATE SEQUENCE AGENCIA_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 10000;
CREATE SEQUENCE EMPLEADO_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100000000;
CREATE SEQUENCE EMPLEADO_AGENCIA_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100000000;
CREATE SEQUENCE CLIENTE_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100000000;
CREATE SEQUENCE HABITACION_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 10000000000000;
CREATE SEQUENCE HOTEL_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 100000;
CREATE SEQUENCE HABITACION_HOTEL_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 10000000000000;
CREATE SEQUENCE RESERVA_SEQ_ID START WITH 1 INCREMENT BY 1 MAXVALUE 10000000000000;




/**
 * TABLA TIPO_HABITACION
 * COLUMNA                   INDICE   JUSTIFICION
 * ----------------------------------------------------------------------------
 * ID_TIPO                   NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * DESCRIPCION               NO       LA DESCRIPCION NO SERA USADA EN COMPARACIONES Y JOINS
 */
 
 
/**
 * TABLA CATEGORIA
 * COLUMNA                   INDICE   JUSTIFICION
 * ----------------------------------------------------------------------------
 * ID_CATEGORIA              NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * DESCRIPCION               NO       LA DESCRIPCION NO SERA USADA EN COMPARACIONES Y JOINS
 * IVA                       SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE
 */
CREATE INDEX CATEGORIA_IVA_INDEX ON CATEGORIA(IVA);
 
 
/**
 * TABLA AGENCIA
 * COLUMNA                   INDICE   JUSTIFICION
 * --------------------------------------------------------------------------------------
 * ID_AGENCIA                NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * TELEFONO                  NO       YA ES INDICE
 * NOMBRE                    SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA UN NOMBRE ESPECIFICO
 * COLONIA                   SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA BUSCAR POR COLONIA
 * CALLE                     NO       ES MAS POSIBLE QUE SEA USADO COLONIA QUE CALLE EN CONDICIONES Y JOINS
 */
CREATE INDEX AGENCIA_NOMBRE_INDEX ON AGENCIA(NOMBRE);
CREATE INDEX AGENCIA_COLONIA_INDEX ON AGENCIA(COLONIA);
 
 
/**
 * TABLA EMPLEADO
 * COLUMNA                   INDICE   JUSTIFICION
 * --------------------------------------------------------------------------------------
 * ID_EMPLEADO               NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * TELEFONO                  NO       YA ES INDICE
 * NOMBRE                    SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA UN NOMBRE ESPECIFICO
 * APELLIDO_PATERNO          SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA BUSCAR POR COLONIA
 * APELLIDO_MATERNO          NO       ES MAS POSIBLE QUE SEA USADO APELLIDO_PATERNO QUE APELLIDO_MATERNO EN CONDICIONES Y JOINS
 */
CREATE INDEX EMPLEADO_NOM_INDEX ON EMPLEADO(NOMBRE);
CREATE INDEX EMPLEADO_APATERNO_INDEX ON EMPLEADO(APELLIDO_PATERNO);
 
 
/**
 * TABLA EMPLEADO_AGENCIA
 * COLUMNA                   INDICE   JUSTIFICION
 * --------------------------------------------------------------------------------------
 * ID_EMPLEADO_AGENCIA       NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * ID_EMPLEADO               SI       COMO INDICE SERA USADO ES CLAUSULAS WHERE Y JOIN
 * ID_AGENCIA                SI       COMO INDICE SERA USADO ES CLAUSULAS WHERE Y JOIN
 */
CREATE INDEX EMAG_ID_EMPLEADO_INDEX ON EMPLEADO_AGENCIA(ID_EMPLEADO);
CREATE INDEX EMAG_ID_AGENCIA_INDEX ON EMPLEADO_AGENCIA(ID_AGENCIA);
 
 
/**
 * TABLA CLIENTE
 * COLUMNA                   INDICE   JUSTIFICION
 * --------------------------------------------------------------------------------------
 * ID_CLIENTE               NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * TELEFONO                 NO       YA ES INDICE
 * NOMBRE                   SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA UN NOMBRE ESPECIFICO
 * APELLIDO_PATERNO         SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA BUSCAR POR COLONIA
 * APELLIDO_MATERNO         NO       ES MAS POSIBLE QUE SEA USADO APELLIDO_PATERNO QUE APELLIDO_MATERNO EN CONDICIONES Y JOINS
 * COLONIA                  SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA BUSCAR POR COLONIA
 * CALLE                    NO       ES MAS POSIBLE QUE SEA USADO COLONIA QUE CALLE EN CONDICIONES Y JOINS
 */
CREATE INDEX CLIENTE_NOM_INDEX ON CLIENTE(NOMBRE);
CREATE INDEX CLIENTE_APATERNO_INDEX ON CLIENTE(APELLIDO_PATERNO);
CREATE INDEX CLIENTE_COLONIA_INDEX ON CLIENTE(COLONIA);

 
 
/**
 * TABLA HABITACION
 * COLUMNA                   INDICE   JUSTIFICION
 * --------------------------------------------------------------------------------------
 * ID_HABITACION             NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * NOMBRE                    SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA UN NOMBRE ESPECIFICO
 * ID_TIPO                   SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE Y JOINS
 */
CREATE INDEX HABITACION_NOM_INDEX ON HABITACION(NOMBRE);
CREATE INDEX HABITACION_ID_TIPO_INDEX ON HABITACION(ID_TIPO);
 
 
/**
 * TABLA HOTEL
 * COLUMNA                   INDICE   JUSTIFICION
 * ---------------------------------------------------------------------------------------------------------------------
 * ID_HOTEL                  NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * TELEFONO                  SI       TENDRA MUCHAS CONSULTAS EN CLAUSUALAS WHERE Y JOINS Y SON UNICOS
 * NOMBRE                    SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA UN NOMBRE ESPECIFICO
 * FECHA_CONSTRUCCION        SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA COMPARAR FECHAR, ORDENAR O AGRUPAR
 * COLONIA                   SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA BUSCAR POR COLONIA
 * CALLE                     NO       ES MAS POSIBLE QUE SEA USADO COLONIA QUE CALLE EN CONDICIONES Y JOINS
 * ID_CATEGORIA              SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE Y JOINS
 */
CREATE INDEX HOTEL_TEL_INDEX ON HOTEL(TELEFONO);
CREATE INDEX HOTEL_NOM_INDEX ON HOTEL(NOMBRE);
CREATE INDEX HOTEL_FCH_INDEX ON HOTEL(FECHA_CONSTRUCCION);
CREATE INDEX HOTEL_COLONIA_INDEX ON HOTEL(COLONIA);
CREATE INDEX HOTEL_ID_CATEGORIA_INDEX ON HOTEL(ID_CATEGORIA);
 
 
/**
 * TABLA HABITACION_HOTEL
 * COLUMNA                   INDICE   JUSTIFICION
 * ----------------------------------------------------------------------------------------------------------------------
 * ID_HABITACION_HOTEL       NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * ID_HABITACION             SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE Y JOINS
 * ID_HOTEL                  SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE Y JOINS
 * CANTIDAD                  SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE
 */
CREATE INDEX HABHOTEL_IDHABIT_INDEX ON HABITACION_HOTEL(ID_HABITACION);
CREATE INDEX HABHOTEL_IDHOT_INDEX ON HABITACION_HOTEL(ID_HOTEL);
CREATE INDEX HABHOTEL_CANTIDAD_INDEX ON HABITACION_HOTEL(CANTIDAD);
 
 
/**
 * TABLA RESERVA
 * COLUMNA                   INDICE   JUSTIFICION
 * ---------------------------------------------------------------------------------------------------------------------
 * ID_RESERVA                NO       ES PARTE DE LA LLAVE PRIMARIA EN SU TABLA
 * ID_EMPLEADO_AGENCIA       SI       TENDRA MUCHAS CONSULTAS EN CLAUSUALAS WHERE Y JOINS
 * ID_CLIENTE                SI       TENDRA MUCHAS CONSULTAS EN CLAUSUALAS WHERE Y JOINS
 * ID_HABITACION_HOTEL       SI       TENDRA MUCHAS CONSULTAS EN CLAUSUALAS WHERE Y JOINS
 * FECHA_INICIO              SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA COMPARAR FECHAR, ORDENAR O AGRUPAR
 * FECHA_FIN                 SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA COMPARAR FECHAR, ORDENAR O AGRUPAR
 * PRECIO                    SI       ES MUY POSIBLE QUE SEA USADA EN CLAUSULAS WHERE PARA COMPARAR PRECIOS
 */
CREATE INDEX RESERVA_IDEMPAG_INDEX ON RESERVA(ID_EMPLEADO_AGENCIA);
CREATE INDEX RESERVA_IDCLI_INDEX ON RESERVA(ID_CLIENTE);
CREATE INDEX RESERVA_IDEHABHOT_INDEX ON RESERVA(ID_HABITACION_HOTEL);
CREATE INDEX RESERVA_IDFCHIN_INDEX ON RESERVA(FECHA_INICIO);
CREATE INDEX RESERVA_IDFCHFIN_INDEX ON RESERVA(FECHA_FIN);
CREATE INDEX RESERVA_PRECIO_INDEX ON RESERVA(PRECIO);





























