

-- 1
UNDEFINE ENTER_NAME;
SELECT LAST_NAME, HIRE_DATE FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = (
  SELECT DEPARTMENT_ID FROM HR.EMPLOYEES WHERE LAST_NAME='&&ENTER_NAME'
) and LAST_NAME <> '&&ENTER_NAME';
