

-- 4
SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE LOCATION_ID = 1700);

SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE LOCATION_ID = '&ingrese_la_ubicacion');