

CREATE TABLE MY_EMPLOYEE (
ID NUMBER(4) CONSTRAINT MY_EMPLOYEE_ID_PK PRIMARY KEY,
LAST_NAME VARCHAR2(25),
FIRST_NAME VARCHAR2(25),
USERID VARCHAR2(8),
SALARY NUMBER(9, 2)
);

SELECT * FROM MY_EMPLOYEE;

INSERT INTO MY_EMPLOYEE VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);
INSERT INTO MY_EMPLOYEE(ID, LAST_NAME, FIRST_NAME, USERID, SALARY) VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);
