INSERT INTO MY_EMPLOYEE VALUES (&ID, 'Biri', 'Ben', 'bbiri', 1100);
INSERT INTO MY_EMPLOYEE VALUES (&ID, 'Newman', 'Chad', 'cnewman', 750);
COMMIT;

UPDATE MY_EMPLOYEE SET LAST_NAME = 'Drexler' WHERE ID = 3;
SELECT * FROM MY_EMPLOYEE;

UPDATE MY_EMPLOYEE SET SALARY = 1000 WHERE SALARY < 900;

DELETE FROM MY_EMPLOYEE WHERE ID = 2;

COMMIT;

INSERT INTO MY_EMPLOYEE VALUES (&ID, 'Ropeburn', 'Audrey', 'aropebur', 1550);

SAVEPOINT insert_id5;

DELETE FROM MY_EMPLOYEE;

SELECT * FROM MY_EMPLOYEE;

ROLLBACK TO insert_id5;

COMMIT;
